; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
framework = arduino
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board_build.partitions = huge_app.csv
lib_deps =
	https://github.com/mlesniew/PicoMQTT
	https://github.com/mlesniew/PicoWebsocket
	https://github.com/bblanchon/ArduinoJson
	https://github.com/mathertel/OneButton


monitor_filters = esp32_exception_decoder
monitor_speed = 115200
build_type = debug

[credentials]
wifi_ssids =
	-DWIFI_SSID=\"${sysenv.WIFI_SSID}\"
	-DWIFI_PASS=\"${sysenv.WIFI_PASSWORD}\"

[common]
flags =
	-g -O2
	-DPICOWEBSOCKET_MAX_HTTP_LINE_LENGTH=512
	; -DCORE_DEBUG_LEVEL=4
	-DCORE_DEBUG_LEVEL=2
	-DCUSTOM_ARDUINO_LOOP_STACK_SIZE=32768

[env:atom-s3u]
board = esp32-s3-devkitc-1
debug_tool = esp-builtin
debug_init_break = tbreak app_main
build_flags =
	${common.flags}
	${credentials.wifi_ssids}
	-DBUTTON_PIN=GPIO_NUM_41
	-DARDUINO_USB_CDC_ON_BOOT=1


[env:seeed_xiao_esp32c6]
board = seeed_xiao_esp32c6
debug_tool = esp-builtin
debug_init_break = tbreak app_main
build_flags =
	${common.flags}
	${credentials.wifi_ssids}
	-DARDUINO_USB_CDC_ON_BOOT=1

[env:m5stack_nanoc6]
board = m5stack_nanoc6

debug_tool = esp-builtin
debug_init_break = tbreak app_main
build_flags =
	${common.flags}
	${credentials.wifi_ssids}
	-DBUTTON_PIN=GPIO_NUM_9
	-DARDUINO_USB_CDC_ON_BOOT=1

[env:m5stick-c]
board = esp32dev
upload_speed = 115200
build_flags =
	${common.flags}
	${credentials.wifi_ssids}
	-DBUTTON_PIN=GPIO_NUM_37

[env:m5stamp-c3u]
board = esp32-c3-devkitc-02
monitor_speed = 115200
upload_speed = 115200
debug_tool = esp-builtin
debug_init_break = tbreak app_main
build_flags =
	${common.flags}
	${credentials.wifi_ssids}
	-DM5STAMP_C3U
	-DBUTTON_PIN=GPIO_NUM_9
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
    -DBUILTIN_RGBLED_PIN=2

[env:esp32p4_waveshare_devkit]
board = esp32-p4-evboard
debug_tool = esp-builtin
debug_init_break = tbreak setup
build_flags =
	${common.flags}
	${credentials.wifi_ssids}
	-g
	-DBOARD_HAS_PSRAM
	-DARDUINO_ESP32P4_DEV_MODULE
	-DCONFIG_SPIRAM_USE_MALLOC
	-DCONFIG_SPIRAM_CACHE_WORKAROUND


[env:atoms3]
board = esp32-s3-devkitc-1
debug_tool = esp-builtin
build_flags =
	${common.flags}
	${credentials.wifi_ssids}



[env:m5stamp-s3]
board = m5stack-stamps3
debug_tool = esp-builtin

build_flags =
	${common.flags}
	${credentials.wifi_ssids}
	-DBUILTIN_RGBLED_PIN=21


;https://www.waveshare.com/esp32-c5-wifi6-kit-n16r4.htm?srsltid=AfmBOoo-skHUZ8L4WezGhntAjR4hWqp2EAgZUN2ILSI46e4bMFcGHqhC
; rgb led on pin27
[env:esp32-c5-devkitc1-n16r8]
upload_speed = 1500000
monitor_speed = 115200
board = esp32-c5-devkitc1-n16r8
build_type = debug
; board_build.partitions = app3M_spiffs9M_16MB.csv
debug_tool = esp-builtin
debug_init_break = tbreak setup

build_flags =
	${common.flags}
	${credentials.wifi_ssids}
	-DBUILTIN_RGBLED_PIN=27
